// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD08XDcwiVAY2nghuf259-iKaaH8LvqFjw',
    appId: '1:862512504967:web:4af39352aa3a437be99822',
    messagingSenderId: '862512504967',
    projectId: 'cointale-7874c',
    authDomain: 'cointale-7874c.firebaseapp.com',
    storageBucket: 'cointale-7874c.firebasestorage.app',
    measurementId: 'G-K5ZJR2FYLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhetDEZmduEHYPZFA5skngw5-Vx4WpxVA',
    appId: '1:862512504967:android:6ed8c1c059f3ac13e99822',
    messagingSenderId: '862512504967',
    projectId: 'cointale-7874c',
    storageBucket: 'cointale-7874c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC92eEncps0FqKUuLwU633oM6c3iRWBPl8',
    appId: '1:862512504967:ios:d5258a37e5ebdb38e99822',
    messagingSenderId: '862512504967',
    projectId: 'cointale-7874c',
    storageBucket: 'cointale-7874c.firebasestorage.app',
    iosBundleId: 'com.example.cointaleProject',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC92eEncps0FqKUuLwU633oM6c3iRWBPl8',
    appId: '1:862512504967:ios:d5258a37e5ebdb38e99822',
    messagingSenderId: '862512504967',
    projectId: 'cointale-7874c',
    storageBucket: 'cointale-7874c.firebasestorage.app',
    iosBundleId: 'com.example.cointaleProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD08XDcwiVAY2nghuf259-iKaaH8LvqFjw',
    appId: '1:862512504967:web:7b03507f5ad9abece99822',
    messagingSenderId: '862512504967',
    projectId: 'cointale-7874c',
    authDomain: 'cointale-7874c.firebaseapp.com',
    storageBucket: 'cointale-7874c.firebasestorage.app',
    measurementId: 'G-X2RMF2RYM7',
  );
}
